"""add_first_migration

Revision ID: 8ec838294ad6
Revises: 
Create Date: 2024-12-30 10:01:54.125512

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ec838294ad6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requestlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("service_name", sa.Text(), nullable=True),
        sa.Column("processing_time", sa.Float(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("tracker_id", sa.String(length=100), nullable=True),
        sa.Column("ip", sa.String(length=50), nullable=True),
        sa.Column("request", sa.Text(), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("trace", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("start_processing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requestlog_created"), "requestlog", ["created"], unique=False
    )
    op.create_index(
        op.f("ix_requestlog_is_deleted"), "requestlog", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_requestlog_modified"), "requestlog", ["modified"], unique=False
    )
    op.create_index(
        op.f("ix_requestlog_start_processing_at"),
        "requestlog",
        ["start_processing_at"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("roles", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("is_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_created"), "user", ["created"], unique=False)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    op.create_index(op.f("ix_user_is_deleted"), "user", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_user_modified"), "user", ["modified"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_modified"), table_name="user")
    op.drop_index(op.f("ix_user_is_deleted"), table_name="user")
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_created"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_requestlog_start_processing_at"), table_name="requestlog")
    op.drop_index(op.f("ix_requestlog_modified"), table_name="requestlog")
    op.drop_index(op.f("ix_requestlog_is_deleted"), table_name="requestlog")
    op.drop_index(op.f("ix_requestlog_created"), table_name="requestlog")
    op.drop_table("requestlog")
    # ### end Alembic commands ###
